[package]
name = "ud-co2s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
regex = "1.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
serial = "0.4.0"
